Binding Validation ------------------
In RecipeController, we previously added MVC validation using the @Valid annotation, but this doesn't work for the reactive stack!!!

	// Add @Valid to the Modelattribute parameter to trigger Bean Validation. Make sure to add the model attribute name if the parameter type name doesn't match the object name in the form in the th:object Thymeleaf attribute. Add BindingResult parameters which will contains the validation result.
	@PostMapping("")
	public String saveRecipe(@Valid @ModelAttribute("recipe") RecipeDTO recipe, BindingResult bindingResult) {
		...
	}

When you try to update a recipe, you get an error like this

	[8dd8c7a3-4, L:/0:0:0:0:0:0:0:1:666 - R:/0:0:0:0:0:0:0:1:55583] There was an unexpected error (type=Internal Server Error, status=500).
	An Errors/BindingResult argument is expected immediately after the @ModelAttribute argument to which it applies. For @RequestBody and @RequestPart arguments, please declare them with a reactive type wrapper and use its onError operators to handle WebExchangeBindException: public java.lang.String guru.springframework.spring5recipeapp.controller.RecipeController.saveRecipe(guru.springframework.spring5recipeapp.dto.RecipeDTO,org.springframework.validation.BindingResult)
	java.lang.IllegalStateException: An Errors/BindingResult argument is expected immediately after the @ModelAttribute argument to which it applies. For @RequestBody and @RequestPart arguments, please declare them with a reactive type wrapper and use its onError operators to handle WebExchangeBindException: public java.lang.String guru.springframework.spring5recipeapp.controller.RecipeController.saveRecipe(guru.springframework.spring5recipeapp.dto.RecipeDTO,org.springframework.validation.BindingResult)
		at org.springframework.util.Assert.state(Assert.java:97)
		Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:

As the validation via parameter annotations isn't playing nice, we will have to workaround it by performing the bean validation and getting the validation (or binding) result the old-fashioned way:
Add this to the top of the Controller class

	// Manually get a handle on the binding framework within Spring
    private WebDataBinder webDataBinder;

    @InitBinder
    public void initBinder(WebDataBinder webDataBinder) {
        this.webDataBinder = webDataBinder;
    }

	And change the controller method like: remove the parameter annotation @Valid and the BindingResult parameter

	@PostMapping("")
    public String saveRecipe(@ModelAttribute("recipe") RecipeDTO recipe) {

        // Manually perform the validation and bind the result, so you can check for validaiton errors
        webDataBinder.validate();
        BindingResult bindingResult = webDataBinder.getBindingResult();

        // Check validation result, log any validation errors and in that case return to the recipe form
        if (bindingResult.hasErrors()) {
            bindingResult.getAllErrors().forEach(objectError -> log.debug(objectError.toString()));

            return VIEWS_RECIPES_FORM;
        }

        RecipeDTO savedRecipeDTO = recipeService.save(recipe).block();

        return VIEWS_RECIPES_REDIRECT + savedRecipeDTO.getId(); // Use MVC redirect to redirect user to the Recipe Detail page (so the browser should load a new url here)
    }