Introduction to Spring Framework WebFlux ________________________________________
Spring WebFlux Dependencies
---------------------------

We will migrate from spring-webmvc to spring-webflux
And from Servlet API to HTTP / Reactive Streams

	WebFlux can run on Servlet containers with support for the Servlet 3.1 Non-Blocking IO API as well as on other async runtimes such as Netty and Undertow. Each runtime is adapted to a reactive ServerHttpRequest and ServerHttpResponse

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

		provides support for 'blocking' Servlet API.
		So we will switch to:

		<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

	We have dependencies directly on the Servlet API (but we removed -starter-web, so these will break the build)

	For example import org.springframework.web.servlet.ModelAndView;

	Just comment out all code which doesn't compile.

	PLEASE NOTE: If you now start up the application, you will see that you are no longer running Tomcat, but Netty application server.

		[INFO] Netty started on port(s): 666

	There will also be failing unit tests when they depend on the Servlet API and /or Spring MVC's MockMvc (which too is tied to the Servlet API)

				java.lang.NoClassDefFoundError: org/springframework/web/servlet/DispatcherServlet

			at org.springframework.test.web.servlet.setup.MockMvcBuilders.standaloneSetup(MockMvcBuilders.java:76)
			at guru.springframework.spring5recipeapp.controller.IndexControllerTest.setUp(IndexControllerTest.java:40)
			...
			at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
			at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
			at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
			at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
		Caused by: java.lang.ClassNotFoundException: org.springframework.web.servlet.DispatcherServlet
			at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
			... 69 more

Reactive Thymeleaf Configuration
--------------------------------

	Due to loading in dependency
	Behind the scenes, Spring will use class ThymeleafAutoConfiguration to also load the reactive version of the Thymeleaf web frontend called 'SpringWebFluxTemplateEngine' (You can put debug marks in there and restart the application to see that it stops there)

	This is the regular Spring MVC version (type = SERVLET)

		@ConditionalOnWebApplication(type = Type.SERVLET)
		@ConditionalOnProperty(name = "spring.thymeleaf.enabled", matchIfMissing = true)
		static class ThymeleafWebMvcConfiguration {

	This is the reactive WebFlux version (type = REACTIVE)

		@ConditionalOnWebApplication(type = Type.REACTIVE)
		@ConditionalOnProperty(name = "spring.thymeleaf.enabled", matchIfMissing = true)
		static class ThymeleafReactiveConfiguration {

	Spring will detect this type from the Servlet Container that we are running... (Tomcat or Netty for example)

Going Reactive With Thymeleaf
-----------------------------

	Make sure all the reactive types reach the Thymeleaf web frontend layer. So in the Controller classes, no longer use (.collectList()).block() to return a list of non-Reactive object types.
	So just return the Mono or Flux objects to Thymeleaf.

	Example controller

		@Controller
		@Slf4j
		public class IndexController {

			private final RecipeService recipeService;

			@Autowired
			public IndexController(RecipeService recipeService) {
				this.recipeService = recipeService;
			}

			@RequestMapping({"", "/", "/index", "/index.html"})
			public String getIndexPage(Model model) {
				log.debug("Running IndexController - getIndexPage()...");
				model.addAttribute("recipes", recipeService.findAll());	// Return the reactive Flux object here

				return "index";
			}
		}

	PLEASE NOTE: Before we used MockMvc to test the Controller classes, but this is tied to Spring MVC. As we removed that, this will no longer work.
					Luckily for WebFlux implementations there is a WebTestClient which works in a similar fashion.

		- You need to add this at the top of your test
			@ExtendWith(SpringExtension.class)
			@WebFluxTest(controllers = IndexController.class)

		- Replace @Mock with @MockBean for the dependencies

		- Add
			@Autowired
			private WebTestClient webTestClient;

		You are now set up for controller testing... Happy testing :-)

			package guru.springframework.spring5recipeapp.controller;

			import guru.springframework.spring5recipeapp.dto.RecipeDTO;
			import guru.springframework.spring5recipeapp.service.RecipeService;

			import org.junit.jupiter.api.Test;
			import org.junit.jupiter.api.extension.ExtendWith;

			import org.springframework.beans.factory.annotation.Autowired;
			import org.springframework.boot.test.autoconfigure.web.reactive.WebFluxTest;
			import org.springframework.boot.test.mock.mockito.MockBean;
			import org.springframework.test.context.junit.jupiter.SpringExtension;
			import org.springframework.test.web.reactive.server.WebTestClient;

			import reactor.core.publisher.Flux;

			import java.util.Objects;

			import static org.junit.jupiter.api.Assertions.assertTrue;
			import static org.mockito.Mockito.*;

			@ExtendWith(SpringExtension.class)
			@WebFluxTest(controllers = IndexController.class)
			class IndexControllerTest {

				@MockBean
				private RecipeService mockRecipeService;

				@Autowired
				private WebTestClient webTestClient;

				@Test
				void testIndex() {
					// given
					RecipeDTO expectedRecipe1 = new RecipeDTO();
					expectedRecipe1.setName("Fajita");

					RecipeDTO expectedRecipe2 = new RecipeDTO();
					expectedRecipe2.setName("Taco");

					when(mockRecipeService.findAll()).thenReturn(Flux.just(expectedRecipe1, expectedRecipe2));

					// when

					// then
					webTestClient.get().uri("/")
							.exchange()
							.expectStatus().isOk()
							.expectBody(String.class)
							.consumeWith(response -> {
								String responseBody = Objects.requireNonNull(response.getResponseBody());
								assertTrue(responseBody.contains("Fajita"));
								assertTrue(responseBody.contains("Taco"));
							});

					verify(mockRecipeService, times(1)).findAll();
				}
			}